name: PHP CI

on:
  push:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Source Code
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Check PHP Version
        run: php -v

      - name: Syntax Validation
        run: php -l index.php

      - name: Run Tests
        run: php test.php

  deploy:
    needs: build # Only runs if tests pass
    runs-on: self-hosted
    steps:
      - name: Copy files to Web Directory
        run: |
          echo "Current directory is: $PWD"
          ls -la ${{ github.workspace }}
          sudo rsync -av --delete ${{ github.workspace }}/ /var/www/html/my-php-app/